### ISSUE TITLE
Not complie on Linux with gcc 6.2.1

### ISSUE THREAD

**Issue by xoac** [jonathonl/goodform#3]
Hi there are problem to compile it under Linux. First things is that the <arpa/inet.h> doesn't define htonll()! (double l)
My solution works but it's not c++ standard:
`#define htonll(x) ((1==htonl(1)) ? (x) : ((uint64_t)htonl((x) & 0xFFFFFFFF) << 32) | htonl((x) >> 32))`
`#define ntohll(x) ((1==ntohl(1)) ? (x) : ((uint64_t)ntohl((x) & 0xFFFFFFFF) << 32) | ntohl((x) >> 32))`
The second problem is with 

> /home/sylwek/workspace/goodform/src/json.cpp:318:13: error: ‘wstring_convert’ is not a member of ‘std’

`<codecvt>` not include `wstring_convert`. you should also include `<locale>` in json.cpp 

_I am just a student so I don't guarantee the solutions are proper. I worked on Manjaro updated 29.09.2016_
